import { describe, expect, it } from "vitest";

import { adminClient } from "./helpers/supabase";

/**
 * pool_template is generated by scripts/generate-pool-template.mts from the
 * committed species seed, not written by hand. These tests check the seed
 * migration replayed into a fresh local Supabase actually produced the table
 * ADR-0003 describes.
 */
const POOL_SIZE = 81;
const EEVEE_ID = 133;
const BULBASAUR_ID = 1;

describe("the seeded pool_template table", () => {
  it("has exactly 81 slots, numbered 0 through 80 with no gaps", async () => {
    const { data, error } = await adminClient().from("pool_template").select("slot").order("slot");
    if (error) throw new Error(`Reading pool_template failed: ${JSON.stringify(error)}`);

    expect(data).toHaveLength(POOL_SIZE);
    expect(data?.map((row) => row.slot)).toEqual(Array.from({ length: POOL_SIZE }, (_, i) => i));
  });

  it("gives Eevee three slots and every other line exactly one", async () => {
    const { data, error } = await adminClient().from("pool_template").select("species_id");
    if (error) throw new Error(`Reading pool_template failed: ${JSON.stringify(error)}`);

    const counts = new Map<number, number>();
    for (const row of data ?? []) {
      counts.set(row.species_id, (counts.get(row.species_id) ?? 0) + 1);
    }

    expect(counts.get(EEVEE_ID)).toBe(3);
    for (const [speciesId, count] of counts) {
      if (speciesId !== EEVEE_ID) expect(count).toBe(1);
    }
  });

  it("starts slot 0 as Bulbasaur", async () => {
    const { data, error } = await adminClient().from("pool_template").select("species_id").eq("slot", 0).single();
    if (error) throw new Error(`Reading slot 0 failed: ${JSON.stringify(error)}`);
    expect(data?.species_id).toBe(BULBASAUR_ID);
  });
});
