import type { MetadataRoute } from "next";

/**
 * What an Android home-screen shortcut reads to name and draw itself. iOS
 * ignores this and uses apple-icon.png instead; both are generated by
 * scripts/generate-app-icons.mts from the same sprite.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Poke Tracker",
    short_name: "Poke Tracker",
    description: "A task tracker your Pokémon cares about.",
    start_url: "/",
    display: "standalone",
    // The app's own background and chrome, so the splash screen and status bar
    // do not flash white on launch.
    background_color: "#0a2a14",
    theme_color: "#0a2a14",
    // "any" only: these icons are transparent and edge to edge, so they are
    // not valid maskable artwork — a maskable icon has to bleed past the inner
    // 80% safe zone with a background Android can crop into.
    icons: [192, 512].map((size) => ({
      src: `/icon-${size}.png`,
      sizes: `${size}x${size}`,
      type: "image/png",
      purpose: "any" as const,
    })),
  };
}
