/**
 * Generates the pool_template seed migration from the already-committed
 * species seed migration. Nothing here talks to PokéAPI — the pool's shape is
 * a mechanical fact about the `species` table's own evolves_from_id column,
 * not new information, so it is derived once from that file rather than from
 * a live database.
 *
 * The rule (see docs/adr/0003-fixed-pool-of-instances.md): one instance per
 * root species (evolves_from_id is null), plus one more per extra leaf a
 * root's subtree reaches — so a root with no branching contributes 1
 * instance regardless of how long its chain is, and Eevee, whose subtree has
 * three leaves, contributes 3. Every instance starts as its line's root
 * species; a leaf only decides how many separate instances that root gets.
 *
 * Usage: node scripts/generate-pool-template.mts
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SPECIES_SEED_PATH = path.join(
  REPO_ROOT,
  "supabase",
  "migrations",
  "20260806170100_seed_species.sql",
);
const MIGRATION_PATH = path.join(
  REPO_ROOT,
  "supabase",
  "migrations",
  "20260806180500_seed_pool_template.sql",
);

const EXPECTED_SPECIES_COUNT = 151;
const EXPECTED_ROOT_COUNT = 79;
const EXPECTED_INSTANCE_COUNT = 81;
const EEVEE_ID = 133;
const EEVEE_LEAF_COUNT = 3;

type SpeciesNode = { id: number; evolvesFromId: number | null };

const ROW_PATTERN = /\((\d+),\s*'(?:[^']|'')*',\s*'(?:[^']|'')*',\s*(null|\d+),\s*\d+\)/g;

function parseSpecies(sql: string): SpeciesNode[] {
  const nodes: SpeciesNode[] = [];
  for (const match of sql.matchAll(ROW_PATTERN)) {
    const [, id, evolvesFrom] = match;
    nodes.push({ id: Number(id), evolvesFromId: evolvesFrom === "null" ? null : Number(evolvesFrom) });
  }
  return nodes;
}

/** Every leaf (childless species) reachable under `rootId`, in ascending id order. */
function leavesUnder(rootId: number, childrenById: Map<number, number[]>): number[] {
  const children = childrenById.get(rootId) ?? [];
  if (children.length === 0) return [rootId];
  return children.flatMap((childId) => leavesUnder(childId, childrenById));
}

async function main() {
  const speciesSql = await readFile(SPECIES_SEED_PATH, "utf8");
  const species = parseSpecies(speciesSql);

  if (species.length !== EXPECTED_SPECIES_COUNT) {
    throw new Error(`Expected ${EXPECTED_SPECIES_COUNT} species, found ${species.length}`);
  }

  const childrenById = new Map<number, number[]>();
  for (const node of species) {
    if (node.evolvesFromId === null) continue;
    const siblings = childrenById.get(node.evolvesFromId) ?? [];
    siblings.push(node.id);
    childrenById.set(node.evolvesFromId, siblings);
  }
  for (const siblings of childrenById.values()) siblings.sort((a, b) => a - b);

  const roots = species
    .filter((node) => node.evolvesFromId === null)
    .map((node) => node.id)
    .sort((a, b) => a - b);

  if (roots.length !== EXPECTED_ROOT_COUNT) {
    throw new Error(`Expected ${EXPECTED_ROOT_COUNT} root species, found ${roots.length}`);
  }

  const slots: { speciesId: number }[] = [];
  const branching: { rootId: number; leafCount: number }[] = [];
  for (const rootId of roots) {
    const leaves = leavesUnder(rootId, childrenById);
    if (leaves.length > 1) branching.push({ rootId, leafCount: leaves.length });
    for (let i = 0; i < leaves.length; i++) slots.push({ speciesId: rootId });
  }

  if (slots.length !== EXPECTED_INSTANCE_COUNT) {
    throw new Error(`Expected ${EXPECTED_INSTANCE_COUNT} pool instances, found ${slots.length}`);
  }
  if (branching.length !== 1 || branching[0].rootId !== EEVEE_ID || branching[0].leafCount !== EEVEE_LEAF_COUNT) {
    throw new Error(`Expected only Eevee (${EEVEE_ID}) to branch, with ${EEVEE_LEAF_COUNT} leaves: ${JSON.stringify(branching)}`);
  }

  const rows = slots.map((slot, index) => `  (${index}, ${slot.speciesId})`);
  const migration = `-- Generated by scripts/generate-pool-template.mts from the committed species
-- seed. Do not hand-edit — re-run the generator and commit its output instead.
--
-- One row per pool instance a signup creates, in a fixed slot order: slot 0
-- is the instance active at signup. species_id is the starting (root)
-- species for that slot; Eevee's three branches are the only slots that
-- repeat a species_id. See docs/adr/0003-fixed-pool-of-instances.md.

insert into public.pool_template (slot, species_id)
values
${rows.join(",\n")};
`;

  await writeFile(MIGRATION_PATH, migration);
  console.log(`Wrote ${slots.length} pool slots to ${MIGRATION_PATH}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
