-- Generated by scripts/generate-species.mts from a single PokéAPI run.
-- Do not hand-edit — re-run the generator and commit its output instead.
--
-- Additive: supabase/migrations/20260806170100_seed_species.sql already shipped
-- to the remote database (ADR-0006), so these columns arrive here rather than
-- by editing that file, which an already-applied migration would silently skip.

alter table public.species
  add column zone text,
  add column animated_sprite_path text;

update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/1.gif' where id = 1;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/2.gif' where id = 2;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/3.gif' where id = 3;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/4.gif' where id = 4;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/5.gif' where id = 5;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/6.gif' where id = 6;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/7.gif' where id = 7;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/8.gif' where id = 8;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/9.gif' where id = 9;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/10.gif' where id = 10;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/11.gif' where id = 11;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/12.gif' where id = 12;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/13.gif' where id = 13;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/14.gif' where id = 14;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/15.gif' where id = 15;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/16.gif' where id = 16;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/17.gif' where id = 17;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/18.gif' where id = 18;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/19.gif' where id = 19;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/20.gif' where id = 20;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/21.gif' where id = 21;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/22.gif' where id = 22;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/23.gif' where id = 23;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/24.gif' where id = 24;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/25.gif' where id = 25;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/26.gif' where id = 26;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/27.gif' where id = 27;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/28.gif' where id = 28;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/29.gif' where id = 29;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/30.gif' where id = 30;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/31.gif' where id = 31;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/32.gif' where id = 32;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/33.gif' where id = 33;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/34.gif' where id = 34;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/35.gif' where id = 35;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/36.gif' where id = 36;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/37.gif' where id = 37;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/38.gif' where id = 38;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/39.gif' where id = 39;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/40.gif' where id = 40;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/41.gif' where id = 41;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/42.gif' where id = 42;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/43.gif' where id = 43;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/44.gif' where id = 44;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/45.gif' where id = 45;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/46.gif' where id = 46;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/47.gif' where id = 47;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/48.gif' where id = 48;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/49.gif' where id = 49;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/50.gif' where id = 50;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/51.gif' where id = 51;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/52.gif' where id = 52;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/53.gif' where id = 53;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/54.gif' where id = 54;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/55.gif' where id = 55;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/56.gif' where id = 56;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/57.gif' where id = 57;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/58.gif' where id = 58;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/59.gif' where id = 59;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/60.gif' where id = 60;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/61.gif' where id = 61;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/62.gif' where id = 62;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/63.gif' where id = 63;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/64.gif' where id = 64;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/65.gif' where id = 65;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/66.gif' where id = 66;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/67.gif' where id = 67;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/68.gif' where id = 68;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/69.gif' where id = 69;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/70.gif' where id = 70;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/71.gif' where id = 71;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/72.gif' where id = 72;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/73.gif' where id = 73;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/74.gif' where id = 74;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/75.gif' where id = 75;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/76.gif' where id = 76;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/77.gif' where id = 77;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/78.gif' where id = 78;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/79.gif' where id = 79;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/80.gif' where id = 80;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/81.gif' where id = 81;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/82.gif' where id = 82;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/83.gif' where id = 83;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/84.gif' where id = 84;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/85.gif' where id = 85;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/86.gif' where id = 86;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/87.gif' where id = 87;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/88.gif' where id = 88;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/89.gif' where id = 89;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/90.gif' where id = 90;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/91.gif' where id = 91;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/92.gif' where id = 92;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/93.gif' where id = 93;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/94.gif' where id = 94;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/95.gif' where id = 95;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/96.gif' where id = 96;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/97.gif' where id = 97;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/98.gif' where id = 98;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/99.gif' where id = 99;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/100.gif' where id = 100;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/101.gif' where id = 101;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/102.gif' where id = 102;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/103.gif' where id = 103;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/104.gif' where id = 104;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/105.gif' where id = 105;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/106.gif' where id = 106;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/107.gif' where id = 107;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/108.gif' where id = 108;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/109.gif' where id = 109;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/110.gif' where id = 110;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/111.gif' where id = 111;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/112.gif' where id = 112;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/113.gif' where id = 113;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/114.gif' where id = 114;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/115.gif' where id = 115;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/116.gif' where id = 116;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/117.gif' where id = 117;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/118.gif' where id = 118;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/119.gif' where id = 119;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/120.gif' where id = 120;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/121.gif' where id = 121;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/122.gif' where id = 122;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/123.gif' where id = 123;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/124.gif' where id = 124;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/125.gif' where id = 125;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/126.gif' where id = 126;
update public.species set zone = 'forest', animated_sprite_path = '/species/animated/127.gif' where id = 127;
update public.species set zone = 'savannah', animated_sprite_path = '/species/animated/128.gif' where id = 128;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/129.gif' where id = 129;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/130.gif' where id = 130;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/131.gif' where id = 131;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/132.gif' where id = 132;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/133.gif' where id = 133;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/134.gif' where id = 134;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/135.gif' where id = 135;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/136.gif' where id = 136;
update public.species set zone = 'meadow', animated_sprite_path = '/species/animated/137.gif' where id = 137;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/138.gif' where id = 138;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/139.gif' where id = 139;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/140.gif' where id = 140;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/141.gif' where id = 141;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/142.gif' where id = 142;
update public.species set zone = 'peak', animated_sprite_path = '/species/animated/143.gif' where id = 143;
update public.species set zone = 'plains', animated_sprite_path = '/species/animated/144.gif' where id = 144;
update public.species set zone = 'plains', animated_sprite_path = '/species/animated/145.gif' where id = 145;
update public.species set zone = 'plains', animated_sprite_path = '/species/animated/146.gif' where id = 146;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/147.gif' where id = 147;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/148.gif' where id = 148;
update public.species set zone = 'marshland', animated_sprite_path = '/species/animated/149.gif' where id = 149;
update public.species set zone = 'plains', animated_sprite_path = '/species/animated/150.gif' where id = 150;
update public.species set zone = 'plains', animated_sprite_path = '/species/animated/151.gif' where id = 151;

alter table public.species
  alter column zone set not null,
  alter column animated_sprite_path set not null,
  add constraint species_zone_check check (zone in ('forest', 'marshland', 'meadow', 'peak', 'plains', 'savannah'));

comment on column public.species.zone is
  'The habitat this species stands in on the Safari Zone encounter view — one of six real Safari Zone areas. Belongs to the species, not any instance: every instance of a given species is met in the same zone.';
comment on column public.species.animated_sprite_path is
  'An animated battle sprite for the encounter view only. The static sprite_path above continues to serve Pokédex tiles and Logbook rows.';
